services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: invoice-assistant-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice_assistant_db
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey
    ports:
      - "16379:6379"

volumes:
  postgres-data: